apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cps-nlp-api.fullname" . }}-config
  labels:
    {{- include "cps-nlp-api.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- tpl (.Files.Get "config/config.json") . | nindent 4 }}
