apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cps-nlp-api.fullname" . }}-secrets
  labels:
    {{- include "cps-nlp-api.labels" . | nindent 4 }}
stringData:
  secret.config.json: |-
    {{- tpl (.Files.Get "config/secret.config.json") . | nindent 4 }}
